run:
  timeout: "5m"

issues:
  exclude-dirs:
    - "internal/codegen/golang/pieces/coretypes"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
