# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build all the binaries for all platforms
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ./dist/urpc-lsp-linux-amd64 ./cmd/urpc-lsp/.
      - GOOS=linux GOARCH=arm64 go build -o ./dist/urpc-lsp-linux-arm64 ./cmd/urpc-lsp/.
      - GOOS=windows GOARCH=amd64 go build -o ./dist/urpc-lsp-windows-amd64.exe ./cmd/urpc-lsp/.
      - GOOS=windows GOARCH=arm64 go build -o ./dist/urpc-lsp-windows-arm64.exe ./cmd/urpc-lsp/.
      - GOOS=darwin GOARCH=amd64 go build -o ./dist/urpc-lsp-darwin-amd64 ./cmd/urpc-lsp/.
      - GOOS=darwin GOARCH=arm64 go build -o ./dist/urpc-lsp-darwin-arm64 ./cmd/urpc-lsp/.

  test:
    desc: Test all code on this repo
    cmd: go test ./...

  lint:
    desc: Lint all code on this repo
    cmd: golangci-lint run ./...

  fmt:
    desc: Format all code on this repo
    cmds:
      - go fmt ./...
      - deno fmt

  fixperms:
    desc: Fix permissions on all files
    cmd: chmod -R 777 .
