# https://taskfile.dev

version: "3"

tasks:
  deps:
    desc: Install all dependencies for the project
    cmds:
      - cd ./urpc && go mod download
      - cd ./playground && npm install

  build:
    desc: Builds the WASM binary, the Playground and the URPC binary
    cmds:
      - cd ./urpc && task build:wasm # <- Required by the playground
      - cd ./playground && npm run build # <- Required by the final URPC binary
      - cd ./urpc && task build:urpc

  test:
    desc: Run all repository tests
    cmds:
      - cd ./urpc && task test
      - cd ./playground && npm run test

  lint:
    desc: Run all repository linters
    cmds:
      - cd ./urpc && task lint
      - cd ./playground && npm run lint

  fmt:
    desc: Run all repository code formatters
    cmds:
      - prettier . --write # <- Default formatter for the root directory
      # The following commands are specific to each directory that has its
      # own formatter
      - cd ./urpc && task fmt
      - cd ./playground && npm run fmt

  fmt-check:
    desc: Run all repository code formatter checks
    cmds:
      - prettier . --check # <- Default formatter for the root directory
      # The following commands are specific to each directory that has its
      # own formatter
      - cd ./urpc && task fmt-check
      - cd ./playground && npm run fmt-check
