# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build all the binaries for all platforms
    cmds:
      # Build and install as local binary
      - go install ./cmd/urpc/.

      # LINUX builds
      - GOOS=linux GOARCH=amd64 go build -o ./dist/urpc-linux-amd64 ./cmd/urpc/.
      - GOOS=linux GOARCH=arm64 go build -o ./dist/urpc-linux-arm64 ./cmd/urpc/.

      # WINDOWS builds
      - GOOS=windows GOARCH=amd64 go build -o ./dist/urpc-windows-amd64.exe ./cmd/urpc/.
      - GOOS=windows GOARCH=arm64 go build -o ./dist/urpc-windows-arm64.exe ./cmd/urpc/.

      # DARWIN (macOS) builds
      - GOOS=darwin GOARCH=amd64 go build -o ./dist/urpc-darwin-amd64 ./cmd/urpc/.
      - GOOS=darwin GOARCH=arm64 go build -o ./dist/urpc-darwin-arm64 ./cmd/urpc/.

  test:
    desc: Test all code on this repo
    cmd: go test ./...

  lint:
    desc: Lint all code on this repo
    cmd: golangci-lint run ./...

  fmt:
    desc: Format all code on this repo
    cmds:
      - go fmt ./...
      - deno fmt

  fixperms:
    desc: Fix permissions on all files
    cmd: chmod -R 777 .
