# https://taskfile.dev

version: "3"

tasks:
  test:
    desc: Test all code on this repo
    cmd: go test ./...

  lint:
    desc: Lint all code on this repo
    cmd: golangci-lint run ./...

  fmt:
    desc: Format all code on this repo
    cmds:
      - go fmt ./...
      - deno fmt

  fixperms:
    desc: Fix permissions on all files
    cmd: chmod -R 777 .
