# UFO RPC Code generator config file
# Read more at https://github.com/uforg/uforpc

version = 1

schema = "{{schema_path}}"

# Uncomment your desired output language(s) below and then
# run `urpc generate` to execute the code generator.

# [playground]
# output_dir = "./ufogen/playground"
# default_base_url = "http://example.com/api/v1/urpc"
# default_headers = [
#   { key = "X-Foo", value = "bar" },
#   { key = "X-Baz", value = "qux" },
# ]

# [golang]
# output_file = "./ufogen/golang/ufogen.go"
# package_name = "ufogen"
# include_server = true
# include_client = true

# [typescript]
# output_file = "./ufogen/typescript/ufogen.ts"
# include_server = true
# include_client = true
# omit_client_default_fetch = false
