/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumeration of allowed primitive type names.
 */
export type PrimitiveTypeEnum = "string" | "int" | "float" | "boolean" | "datetime";
/**
 * The parameter value(s) passed to the rule instance (null if none).
 */
export type AppliedParameterValue = {
  [k: string]: unknown;
};

export interface Schema {
  /**
   * The version number of the URPC schema specification used.
   */
  version: 1;
  /**
   * An ordered array of all declared elements (nodes) in the URPC schema.
   */
  nodes: (DocumentationNode | RuleDefinitionNode | TypeDefinitionNode | ProcedureDefinitionNode)[];
}
/**
 * Represents a standalone documentation block.
 */
export interface DocumentationNode {
  /**
   * Node type identifier.
   */
  kind: "doc";
  /**
   * The documentation content (Markdown or resolved external file).
   */
  content: string;
}
/**
 * Defines a custom validation rule.
 */
export interface RuleDefinitionNode {
  /**
   * Node type identifier.
   */
  kind: "rule";
  /**
   * Name of the custom rule.
   */
  name: string;
  /**
   * Associated documentation string (optional).
   */
  doc?: string;
  /**
   * Indicates if the rule is deprecated and contains the message associated with the deprecation. Use an empty string to deprecate without a message.
   */
  deprecated?: string;
  /**
   * The primitive or custom type name this rule applies to.
   */
  for: PrimitiveTypeEnum | string;
  paramDef?: ParameterDefinition;
  /**
   * Default error message for the rule (optional).
   */
  error?: string;
}
/**
 * Definition of the parameter this rule expects (null if none).
 */
export interface ParameterDefinition {
  /**
   * The primitive type expected for the parameter (excluding datetime).
   */
  type: "string" | "int" | "float" | "boolean";
  /**
   * Indicates if the parameter is expected to be an array of the specified type.
   */
  isArray: boolean;
}
/**
 * Defines a custom data type.
 */
export interface TypeDefinitionNode {
  /**
   * Node type identifier.
   */
  kind: "type";
  /**
   * Name of the custom type.
   */
  name: string;
  /**
   * Associated documentation string (optional).
   */
  doc?: string;
  /**
   * Indicates if the type is deprecated and contains the message associated with the deprecation. Use an empty string to deprecate without a message.
   */
  deprecated?: string;
  /**
   * Ordered list of fields within the type.
   */
  fields?: FieldDefinition[];
}
/**
 * Defines a field within a type or procedure input/output.
 */
export interface FieldDefinition {
  /**
   * Name of the field.
   */
  name: string;
  /**
   * Name of the primitive or custom type (used if the type is not inline).
   */
  typeName?: string;
  typeInline?: InlineTypeDefinition;
  /**
   * Array dimensions (0 for scalar, 1 for T[], 2 for T[][], etc.).
   */
  depth: number;
  /**
   * Indicates if the field is optional.
   */
  optional: boolean;
  /**
   * List of validation rules applied to this field.
   */
  rules?: AppliedRule[];
}
/**
 * Definition of the inline object type (used if the type is not named).
 */
export interface InlineTypeDefinition {
  /**
   * Ordered list of fields within the inline type.
   */
  fields: FieldDefinition[];
}
/**
 * Represents a validation rule applied to a field, including its parameters.
 */
export interface AppliedRule {
  /**
   * Name of the validation rule being applied.
   */
  rule: string;
  param?: AppliedParameterValue;
  /**
   * Custom error message overriding the rule's default (optional).
   */
  error?: string;
}
/**
 * Defines an RPC procedure.
 */
export interface ProcedureDefinitionNode {
  /**
   * Node type identifier.
   */
  kind: "proc";
  /**
   * Name of the procedure.
   */
  name: string;
  /**
   * Associated documentation string (optional).
   */
  doc?: string;
  /**
   * Indicates if the procedure is deprecated and contains the message associated with the deprecation. Use an empty string to deprecate without a message.
   */
  deprecated?: string;
  /**
   * Ordered list of input fields for the procedure.
   */
  input?: FieldDefinition[];
  /**
   * Ordered list of output fields for the procedure.
   */
  output?: FieldDefinition[];
  /**
   * Optional key-value metadata associated with the procedure (null if none).
   */
  meta?: MetaDefinition[];
}
/**
 * Defines a meta within a procedure.
 */
export interface MetaDefinition {
  /**
   * Key of the meta.
   */
  key: string;
  /**
   * Value of the meta.
   */
  value: string | number | boolean;
}
